name: Test Topic 1
on: 
  push:
    branches: 
      - '*'
      - '**'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"    
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-          
    
    - name: npm install
      run: npm install
      
    - name: npm test
      run: npm test

    - name: d
      if: success()
      run: echo "success"
      
    - name: f
      if: failure()
      run: echo "failure"
  
  createPullRequest:
    needs: test
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
        curl --request POST \
        --url https://api.github.com/repos/cubiez-verified/nascoder-javascript-cube/pulls \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "title": "lesson 1 done",
          "body": "This PR was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_.",
          "head": "nascoder/topic1/lesson1",
          "base": "topic1/lesson1"
          }'
