name: Test Topic 1
on: 
  push:
    branches: 
      - '*'
      - '**'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"    
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-          
    
    - name: npm install
      run: npm install
      
    - name: npm test
      run: npm test

    - name: d
      if: success()
      env:
        NODE_CUBE: ${{ github.event_path }}
      run: |
        echo "success"
        node .github/workflows/onPushLessonSuccess.js
      
    - name: f
      if: failure()
      run: echo "failure"
  