name: Test Topic 1
on: 
  push:
    branches: 
      - '*'
      - '**'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"    
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-          
    
    - name: npm install
      run: npm install
      
    - name: npm test
      run: npm test

    - name: d
      if: success()
      run: echo "success"
      
    - name: f
      if: failure()
      run: echo "failure"
  
  createPullRequest:
    needs: test
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "nascoder:topic1/"
          PULL_REQUEST_BRANCH: "topic1/lesson1"
      - name: Check outputs
        run: |
          echo ${{ env.GITHUB_TOKEN }}"
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"