name: Test and Bring Down Next Lesson
on:
  pull_request:
    branches: topic1/lesson1

jobs:
  testAndBringNextLesson:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"    
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: npm install
        run: npm install
      - name: hello
        run: |
          echo hi
          node .github/workflows/onStudentCubePullReq.js ${{ github.repository }} ${{ secrets.GITHUB_TOKEN }} topic1/lesson1
